Avoid to use `getClientRects().map`
Because the `map` throw the error on Firefox:

```
NoSuchMethodError: Cannot call "get$length" (J.getInterceptor$asx(...).get$length is not a function)

Stacktrace:
J.get$length$asx@http://127.0.0.1:8080/index.html_bootstrap.dart.js:21933:3
.MappedListIterable.get$length@http://127.0.0.1:8080/index.html_bootstrap.dart.js:4842:7
.ListIterable.fold$2@http://127.0.0.1:8080/index.html_bootstrap.dart.js:4651:7
._getTopLeftPoint@http://127.0.0.1:8080/index.html_bootstrap.dart.js:13625:146
.FoldButtonElement._foldTarget$0@http://127.0.0.1:8080/index.html_bootstrap.dart.js:13688:11
...
```